# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- 6.0

pr:
- master

variables:
  MATLAB_VER: R2019b

jobs:

- job: windows
  timeoutInMinutes: 360

  variables:
    buildPlatform: 'windows'

  pool:
    name: Default
    demands: 
    - Matlab -equals 2019b
    - Agent.OS -equals Windows_NT

  steps:
  - checkout: self 
    clean: true
    submodules: recursive

  - bash: echo "##vso[task.setvariable variable=version]$(git describe)"
    displayName: 'Determine version'

  - script: .\BuildFLIMfit.bat
    displayName: 'Build FLIMfit frontend'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/FLIMfitStandalone/Installer/'
      Contents: '*.exe'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/build'
      CleanTargetFolder: true

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'FLIMfit-$(buildPlatform)'
      targetPath: '$(Build.ArtifactStagingDirectory)/build/FLIMfit $(version) Setup x64.exe'

  - task: AzureFileCopy@3
    inputs:
      SourcePath: '$(Build.ArtifactStagingDirectory)/build/FLIMfit $(version) Setup x64.exe'
      azureSubscription: 'Pay-As-You-Go(a38da80c-0896-448b-9c6b-271c458ac013)'
      Destination: 'AzureBlob'
      storage: 'flimfit'
      ContainerName: 'builds'


