# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- 6.0

pr:
- master

jobs:

- job: osx
  timeoutInMinutes: 360

  variables:
    group: passwords
    VCPKG_ROOT: '$(Build.SourcesDirectory)/env/vcpkg'
    archiveFile: '$(Build.ArtifactStagingDirectory)/flimfit-$(buildPlatform).zip'

  pool:
    name: Default
    demands: 
    - Matlab2018b
    - Agent.OS -equals Darwin

  steps:
  - task: InstallAppleCertificate@2
    condition: eq(variables['buildPlatform'],'osx')
    inputs:
      certSecureFile: 'sean-warren-apple-dev-cert-azure.p12'
      certPwd: '$(apple-dev-cert-password)'
      keychain: 'temp'

  - script: brew install ninja ghostscript platypus coreutils llvm libomp
    displayName: 'Setup environment'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'FLIMfit'
      pipeline: 'FLIMfit vcpkg'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latestFromBranch'
      allowPartiallySucceededBuilds: true
      branchName: 'refs/heads/master'
      artifactName: 'flimfit-env-$(buildPlatform)'
      downloadPath: '$(System.ArtifactsDirectory)' 

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(System.ArtifactsDirectory)/**/*.zip' 
      destinationFolder: '$(Build.SourcesDirectory)/env'
      cleanDestinationFolder: true

  - script: './BuildFLIMfit.sh'
    displayName: 'Build FLIMfit' 

- job: windows
  timeoutInMinutes: 360

  variables:
    VCPKG_ROOT: '$(Build.SourcesDirectory)/env/vcpkg'
    archiveFile: '$(Build.ArtifactStagingDirectory)/flimfit-$(buildPlatform).zip'

  pool:
    name: Default
    demands: 
    - Matlab2018b
    - Agent.OS -equals Windows_NT

  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'FLIMfit'
      pipeline: 'FLIMfit vcpkg'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latestFromBranch'
      allowPartiallySucceededBuilds: true
      branchName: 'refs/heads/master'
      artifactName: 'flimfit-env-$(buildPlatform)'
      downloadPath: '$(System.ArtifactsDirectory)' 

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(System.ArtifactsDirectory)/**/*.zip' 
      destinationFolder: '$(Build.SourcesDirectory)/env'
      cleanDestinationFolder: true

  - script: .\build-mex.bat and .\build-flimfit.bat
    displayName: 'Build FLIMfit'