function addpath_global_analysis()

    if ~isdeployed
        thisdir = fileparts( mfilename( 'fullpath' ) );
        addpath( thisdir,...
                [thisdir filesep 'Classes'],...
                [thisdir filesep 'GUIDEInterfaces'],...
                [thisdir filesep 'GeneratedFiles'],...
                [thisdir filesep 'InternalHelperFunctions'],...
                [thisdir filesep 'InternalHelperFunctions' filesep 'RawDataFunctions'],...
                [thisdir filesep 'HelperFunctions'],...
                [thisdir filesep 'HelperFunctions' filesep 'GUILayout-v1p8'],...
                [thisdir filesep 'HelperFunctions' filesep 'GUILayout-v1p8' filesep 'Patch'],...
                [thisdir filesep 'HelperFunctions' filesep 'GUILayout-v1p8' filesep 'layoutHelp'],...
                [thisdir filesep 'HelperFunctions' filesep 'xml_io_toos'],...
                [thisdir filesep '..' filesep 'GlobalProcessingLibrary' filesep 'Libraries'],...
                [thisdir filesep 'OMEROMatlab'],... 
                [thisdir filesep 'OMEROMatlab' filesep 'helper'],... 
                [thisdir filesep 'OMEROUtilities'],...
                [matlabroot filesep 'toolbox' filesep 'images' filesep 'images']);
            
            %makegenops;
            genops(1);
    end

end