function window = open_window(v)

    window = figure( ...
        'Name', ['FLIMfit ' v], ...
        'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'Toolbar', 'none', ...
        'HandleVisibility', 'off', ...
        'Visible','off', ...
        'CloseRequestFcn', @flim_fit_ui.close_request_fcn,...
        'WindowState', 'maximized');
    
end