function err = call_fitting_lib(obj,roi_mask,selected)

    p = obj.fit_params;
    d = obj.data_series;
    
    if nargin < 3
        selected = [];
    end
    if nargin < 2
        roi_mask = [];
    end

    if d.use_memory_mapping
        
        data_ref = d.tr_mapfile_name;
        
        if p.polarisation_resolved 
            fcn_name = 'FLIMGlobalPolarisationFitMemMap';
        else
            fcn_name = 'FLIMGlobalFitMemMap';
        end
    else
        
        data_ref = obj.p_data;
        
        if p.polarisation_resolved 
            fcn_name = 'FLIMGlobalPolarisationFit';
        else
            fcn_name = 'FLIMGlobalFit';
        end
    end
    
    

    if obj.bin
            
        if obj.grid
    
            nl = p.n_exp - p.n_fix;
            grid_size = 25;

            obj.grid_dims = ones(1,nl)*grid_size;        
            obj.p_grid = libpointer('doublePtr', zeros(obj.grid_dims));

            decay = obj.data_series.get_roi(roi_mask,selected);
            decay = squeeze(nansum(decay,2));

            obj.p_data = libpointer('doublePtr', decay);

            err = calllib(obj.lib_name,'FLIMGlobalGetChi2Map', ...
                                obj.dll_id, p.data_type, obj.p_data, ...
                                length(d.tr_t), obj.p_t, length(d.tr_irf), obj.p_t_irf, obj.p_irf, 0, ...
                                p.n_exp, p.n_fix, ...
                                obj.p_tau_min, obj.p_tau_max, obj.p_tau_guess, ...
                                p.fit_beta, obj.p_fixed_beta, ...
                                0, p.t0, 0, p.offset, ...
                                0, p.scatter, ...
                                p.fit_tvb, p.tvb, obj.p_tvb_profile, ...
                                0, 0, p.inc_donor, 1, ...
                                p.pulsetrain_correction, 1/p.rep_rate, ...
                                p.ref_reconvolution, p.ref_lifetime, ...
                                grid_size, obj.p_grid, ...
                                obj.p_tau, obj.p_I0, obj.p_beta, obj.p_E, obj.p_gamma, ...
                                obj.p_t0, obj.p_offset, obj.p_scatter, obj.p_tvb, obj.p_ref_lifetime, ...
                                obj.p_chi2, true, false, 0);

        else

             decay = obj.data_series.get_roi(roi_mask,selected);
             decay = squeeze(nansum(decay,3));

             obj.p_data = libpointer('doublePtr', decay);

             err = calllib(obj.lib_name,'FLIMGlobalFit', ...
                                obj.dll_id, obj.n_group, obj.n_px, obj.p_n_regions, p.global_fitting, ...
                                p.data_type, obj.p_data, obj.p_mask, ...
                                length(d.tr_t), obj.p_t, length(d.tr_irf), obj.p_t_irf, obj.p_irf, 0, ...
                                p.n_exp, p.n_fix, ...
                                obj.p_tau_min, obj.p_tau_max, obj.single_guess, obj.p_tau_guess, ...
                                p.fit_beta, obj.p_fixed_beta, ...
                                p.fit_t0, p.t0, p.fit_offset, p.offset, ...
                                p.fit_scatter, p.scatter, ...
                                p.fit_tvb, p.tvb, obj.p_tvb_profile, ...
                                p.n_fret, p.n_fret_fix, p.inc_donor, obj.p_E_guess, ...
                                p.pulsetrain_correction, 1/p.rep_rate, ...
                                p.ref_reconvolution, p.ref_lifetime, p.fitting_algorithm, ...
                                obj.p_tau, obj.p_I0, obj.p_beta, obj.p_E, obj.p_gamma, ...
                                obj.p_t0, obj.p_offset, obj.p_scatter, obj.p_tvb, obj.p_ref_lifetime, ...
                                0, obj.p_tau_err, obj.p_beta_err, obj.p_E_err, ...
                                obj.p_offset_err, obj.p_scatter_err, obj.p_tvb_err, obj.p_ref_lifetime_err, ...
                                obj.p_chi2, obj.p_ierr, p.n_thread, true, false, 0);

        end        
     
    else
            
        if p.polarisation_resolved

            err = calllib(obj.lib_name,fcn_name, ...
                                obj.dll_id, obj.n_group, obj.n_px, obj.p_n_regions, double(p.global_fitting), ...
                                p.data_type, data_ref, obj.p_mask, ...
                                length(d.tr_t), obj.p_t, length(d.tr_irf), obj.p_t_irf, obj.p_irf, 0, ...
                                p.n_exp, p.n_fix, ...
                                obj.p_tau_min, obj.p_tau_max, obj.single_guess, obj.p_tau_guess, ...
                                p.fit_beta, obj.p_fixed_beta, ...
                                0, obj.p_magic_decay, ...
                                p.n_theta, p.n_theta_fix, 0, obj.p_theta_guess, ...
                                p.fit_t0, 0, p.fit_offset, p.offset, ...
                                p.fit_scatter, p.scatter, ...
                                p.fit_tvb, p.tvb, obj.p_tvb_profile, ...
                                p.pulsetrain_correction, 1/p.rep_rate, ...
                                p.ref_reconvolution, p.ref_lifetime, p.fitting_algorithm, ...
                                obj.p_tau, obj.p_I0, obj.p_beta, obj.p_theta, obj.p_r, ...
                                obj.p_t0, obj.p_offset, obj.p_scatter, obj.p_tvb, obj.p_ref_lifetime, ...
                                p.calculate_errs, obj.p_tau_err, obj.p_beta_err, obj.p_theta_err, ...
                                obj.p_offset_err, obj.p_scatter_err, obj.p_tvb_err, obj.p_ref_lifetime_err, ...
                                obj.p_chi2, obj.p_ierr, p.n_thread, true, false, 0);
        else

            err = calllib(obj.lib_name,fcn_name, ...
                                obj.dll_id, obj.n_group, obj.n_px, obj.p_n_regions, double(p.global_fitting), ...
                                p.data_type, data_ref, obj.p_mask, ...
                                length(d.tr_t), obj.p_t, length(d.tr_irf), obj.p_t_irf, obj.p_irf, 0, ...
                                p.n_exp, p.n_fix, ...
                                obj.p_tau_min, obj.p_tau_max, obj.single_guess, obj.p_tau_guess, ...
                                p.fit_beta, obj.p_fixed_beta, ...
                                p.fit_t0, 0, p.fit_offset, p.offset, ...
                                p.fit_scatter, p.scatter, ...
                                p.fit_tvb, p.tvb, obj.p_tvb_profile, ...
                                p.n_fret, p.n_fret_fix, p.inc_donor, obj.p_E_guess, ...
                                p.pulsetrain_correction, 1/p.rep_rate, ...
                                p.ref_reconvolution, p.ref_lifetime, p.fitting_algorithm, ...
                                obj.p_tau, obj.p_I0, obj.p_beta, obj.p_E, obj.p_gamma, ...
                                obj.p_t0, obj.p_offset, obj.p_scatter, obj.p_tvb, obj.p_ref_lifetime, ...
                                p.calculate_errs, obj.p_tau_err, obj.p_beta_err, obj.p_E_err, ...
                                obj.p_offset_err, obj.p_scatter_err, obj.p_tvb_err, obj.p_ref_lifetime_err, ...
                                obj.p_chi2, obj.p_ierr, p.n_thread, true, false, 0);
        end

    end